AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mandrill-webhooks

  Sample SAM Template for mandrill-webhooks

Parameters:
  Stage:
    Default: test
    Type: String
    Description: Stage name to deploy resource
    AllowedValues:
      - dev
      - test
      - prod

Globals:
  Function:
    Timeout: 20
    MemorySize: 1024
    Runtime: java21
    Architectures:
      - x86_64
    Environment:
      Variables:
        STAGE: !Ref Stage
    LoggingConfig:
      LogFormat: JSON

Resources:

  WebhooksApi:
    Type: AWS::Serverless::Api
    DependsOn:
      - MandrillWebhooksHandlerFunction
    Properties:
      StageName: !Ref Stage
      EndpointConfiguration: REGIONAL

  WebhooksUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref WebhooksApi
          Stage: !Ref Stage
      UsagePlanName: !Sub "mandrill-webhooks-usage-plan-${Stage}"
      Quota:
        Limit: 1000000
        Period: MONTH
      Throttle:
        BurstLimit: 500
        RateLimit: 1000

  MandrillWebhooksHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MandrillWebhooksFunction
      Handler: com.quickfee.lambda.WebhooksHandler::handleRequest

      Events:
        WebhookPostEvent:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
            RestApiId:
              Ref: WebhooksApi

        WebhookHeadEvent:
          Type: Api
          Properties:
            Path: /webhook
            Method: head
            RestApiId:
              Ref: WebhooksApi

  MandrillWebhookHandlerFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref MandrillWebhooksHandlerFunction
      AuthType: NONE

  PermissionForURLInvoke:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunctionUrl'
      FunctionName: !Ref MandrillWebhooksHandlerFunction
      FunctionUrlAuthType: NONE
      Principal: '*'

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  WebhooksApiUrl:
    Description: API Gateway endpoint URL for prod Mandrill webhooks function
    Value: !Sub "https://${WebhooksApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/webhook"
