name: Deploy Webhooks Lambda

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment:'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean install

#      - name: Set up AWS CLI
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1

#      - name: Deploy SAM Application
#        run: |
#          if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
#            sam deploy --template-file packaged.yaml --stack-name my-lambda-stack-dev --capabilities CAPABILITY_IAM
#          elif [ "${{ github.event.inputs.environment }}" == "test" ]; then
#            sam deploy --template-file packaged.yaml --stack-name my-lambda-stack-test --capabilities CAPABILITY_IAM
#          elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
#            sam deploy --template-file packaged.yaml --stack-name my-lambda-stack-prod --capabilities CAPABILITY_IAM
#          fi