name: Deploy Webhooks Lambda 2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment:'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: |
          cd ${GITHUB_WORKSPACE}/MandrillWebhooksFunction
          mvn clean install

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Package SAM Application
        run: |
          cd ${GITHUB_WORKSPACE}/MandrillWebhooksFunction
          mvn package
          # cp target/MandrillWebhooksFunction-1.0-shaded.jar ${GITHUB_WORKSPACE}/MandrillWebhooksFunction/packaged.yaml
          

      - name: List current directory
        run: ls -a

      - name: What is in the target folder?
        run: |
          cd target
          ls -a
        
